port: "18088"
secret_token: "123abc123"

# MySQL 配置
database:
  driver: mysql
  user: root
  password: P@ssword1
  host: 192.168.0.214:21406
  database: aiops


pipelines:
  - name: bbx_Front_FAT_UAT
    type: frontend
    env: fe-beta
    event_type: push
    script: /home/jenkins/execute/pc/beta/build-deploy.sh

  - name: bbx_Front_Online
    type: frontend
    env: fe-prod
    event_type: push
    script: /home/jenkins/execute/pc/prod/build-prod.sh

  - name: bbx_bbz_OpenBeta_pipline
    type: backend
    env: be-beta
    event_type: push
    script: /home/jenkins/execute/beta/beatenv_build/build-beta.sh

  - name: bbx_bbz_Prod_pipline
    type: backend
    env: be-all-prod
    event_type: tag
    script: /home/jenkins/execute/prod/prod_one_click/build-all-prod.sh

  - name: bbx_bbz_OnlineAlone_pipline
    type: backend
    env: be-prod
    event_type: push
    script: /home/jenkins/execute/prod/prodenv_build/build-prod.sh