port: "18088"
secret_token: "123abc123"

# MySQL 配置
database:
  driver: mysql
  user: root
  password: P@ssword1
  host: 192.168.0.214:21406
  database: aiops


pipelines:
  - name: bbx_Front_FAT_UAT
    type: frontend
    env: fe-beta
    event_type: push
    script: /home/youxihu/mytest/QucikBrick/fe-beta.sh

  - name: bbx_Front_Online
    type: frontend
    env: fe-prod
    event_type: push
    script: /home/youxihu/mytest/QucikBrick/fe-prod.sh

  - name: bbx_bbz_OpenBeta_pipline
    type: backend
    env: be-beta
    event_type: push
    script: /home/youxihu/mytest/QucikBrick/be-beta.sh

  - name: bbx_bbz_Prod_pipline
    type: backend
    env: be-all-prod
    event_type: tag
    script: /home/youxihu/mytest/QucikBrick/be-tag.sh

  - name: bbx_bbz_OnlineAlone_pipline
    type: backend
    env: be-prod
    event_type: push
    script: /home/youxihu/mytest/QucikBrick/be-prod.sh