// Code generated by ent, DO NOT EDIT.

package ent

import (
	"QuickBrick/internal/domain/ent/predicate"
	"QuickBrick/internal/domain/ent/retryhistory"
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeRetryHistory = "RetryHistory"
)

// RetryHistoryMutation represents an operation that mutates the RetryHistory nodes in the graph.
type RetryHistoryMutation struct {
	config
	op             Op
	typ            string
	id             *int64
	created_at     *time.Time
	env            *string
	project        *string
	project_url    *string
	ref            *string
	event_type     *string
	commit_id      *string
	committer      *string
	commit_message *string
	commit_url     *string
	pipeline_name  *string
	pipeline_type  *string
	clearedFields  map[string]struct{}
	done           bool
	oldValue       func(context.Context) (*RetryHistory, error)
	predicates     []predicate.RetryHistory
}

var _ ent.Mutation = (*RetryHistoryMutation)(nil)

// retryhistoryOption allows management of the mutation configuration using functional options.
type retryhistoryOption func(*RetryHistoryMutation)

// newRetryHistoryMutation creates new mutation for the RetryHistory entity.
func newRetryHistoryMutation(c config, op Op, opts ...retryhistoryOption) *RetryHistoryMutation {
	m := &RetryHistoryMutation{
		config:        c,
		op:            op,
		typ:           TypeRetryHistory,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRetryHistoryID sets the ID field of the mutation.
func withRetryHistoryID(id int64) retryhistoryOption {
	return func(m *RetryHistoryMutation) {
		var (
			err   error
			once  sync.Once
			value *RetryHistory
		)
		m.oldValue = func(ctx context.Context) (*RetryHistory, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().RetryHistory.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRetryHistory sets the old RetryHistory of the mutation.
func withRetryHistory(node *RetryHistory) retryhistoryOption {
	return func(m *RetryHistoryMutation) {
		m.oldValue = func(context.Context) (*RetryHistory, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RetryHistoryMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RetryHistoryMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of RetryHistory entities.
func (m *RetryHistoryMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RetryHistoryMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RetryHistoryMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().RetryHistory.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *RetryHistoryMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *RetryHistoryMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the RetryHistory entity.
// If the RetryHistory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RetryHistoryMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *RetryHistoryMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetEnv sets the "env" field.
func (m *RetryHistoryMutation) SetEnv(s string) {
	m.env = &s
}

// Env returns the value of the "env" field in the mutation.
func (m *RetryHistoryMutation) Env() (r string, exists bool) {
	v := m.env
	if v == nil {
		return
	}
	return *v, true
}

// OldEnv returns the old "env" field's value of the RetryHistory entity.
// If the RetryHistory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RetryHistoryMutation) OldEnv(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEnv is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEnv requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEnv: %w", err)
	}
	return oldValue.Env, nil
}

// ResetEnv resets all changes to the "env" field.
func (m *RetryHistoryMutation) ResetEnv() {
	m.env = nil
}

// SetProject sets the "project" field.
func (m *RetryHistoryMutation) SetProject(s string) {
	m.project = &s
}

// Project returns the value of the "project" field in the mutation.
func (m *RetryHistoryMutation) Project() (r string, exists bool) {
	v := m.project
	if v == nil {
		return
	}
	return *v, true
}

// OldProject returns the old "project" field's value of the RetryHistory entity.
// If the RetryHistory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RetryHistoryMutation) OldProject(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProject is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProject requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProject: %w", err)
	}
	return oldValue.Project, nil
}

// ResetProject resets all changes to the "project" field.
func (m *RetryHistoryMutation) ResetProject() {
	m.project = nil
}

// SetProjectURL sets the "project_url" field.
func (m *RetryHistoryMutation) SetProjectURL(s string) {
	m.project_url = &s
}

// ProjectURL returns the value of the "project_url" field in the mutation.
func (m *RetryHistoryMutation) ProjectURL() (r string, exists bool) {
	v := m.project_url
	if v == nil {
		return
	}
	return *v, true
}

// OldProjectURL returns the old "project_url" field's value of the RetryHistory entity.
// If the RetryHistory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RetryHistoryMutation) OldProjectURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProjectURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProjectURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProjectURL: %w", err)
	}
	return oldValue.ProjectURL, nil
}

// ResetProjectURL resets all changes to the "project_url" field.
func (m *RetryHistoryMutation) ResetProjectURL() {
	m.project_url = nil
}

// SetRef sets the "ref" field.
func (m *RetryHistoryMutation) SetRef(s string) {
	m.ref = &s
}

// Ref returns the value of the "ref" field in the mutation.
func (m *RetryHistoryMutation) Ref() (r string, exists bool) {
	v := m.ref
	if v == nil {
		return
	}
	return *v, true
}

// OldRef returns the old "ref" field's value of the RetryHistory entity.
// If the RetryHistory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RetryHistoryMutation) OldRef(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRef is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRef requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRef: %w", err)
	}
	return oldValue.Ref, nil
}

// ResetRef resets all changes to the "ref" field.
func (m *RetryHistoryMutation) ResetRef() {
	m.ref = nil
}

// SetEventType sets the "event_type" field.
func (m *RetryHistoryMutation) SetEventType(s string) {
	m.event_type = &s
}

// EventType returns the value of the "event_type" field in the mutation.
func (m *RetryHistoryMutation) EventType() (r string, exists bool) {
	v := m.event_type
	if v == nil {
		return
	}
	return *v, true
}

// OldEventType returns the old "event_type" field's value of the RetryHistory entity.
// If the RetryHistory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RetryHistoryMutation) OldEventType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEventType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEventType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEventType: %w", err)
	}
	return oldValue.EventType, nil
}

// ResetEventType resets all changes to the "event_type" field.
func (m *RetryHistoryMutation) ResetEventType() {
	m.event_type = nil
}

// SetCommitID sets the "commit_id" field.
func (m *RetryHistoryMutation) SetCommitID(s string) {
	m.commit_id = &s
}

// CommitID returns the value of the "commit_id" field in the mutation.
func (m *RetryHistoryMutation) CommitID() (r string, exists bool) {
	v := m.commit_id
	if v == nil {
		return
	}
	return *v, true
}

// OldCommitID returns the old "commit_id" field's value of the RetryHistory entity.
// If the RetryHistory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RetryHistoryMutation) OldCommitID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCommitID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCommitID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCommitID: %w", err)
	}
	return oldValue.CommitID, nil
}

// ResetCommitID resets all changes to the "commit_id" field.
func (m *RetryHistoryMutation) ResetCommitID() {
	m.commit_id = nil
}

// SetCommitter sets the "committer" field.
func (m *RetryHistoryMutation) SetCommitter(s string) {
	m.committer = &s
}

// Committer returns the value of the "committer" field in the mutation.
func (m *RetryHistoryMutation) Committer() (r string, exists bool) {
	v := m.committer
	if v == nil {
		return
	}
	return *v, true
}

// OldCommitter returns the old "committer" field's value of the RetryHistory entity.
// If the RetryHistory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RetryHistoryMutation) OldCommitter(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCommitter is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCommitter requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCommitter: %w", err)
	}
	return oldValue.Committer, nil
}

// ResetCommitter resets all changes to the "committer" field.
func (m *RetryHistoryMutation) ResetCommitter() {
	m.committer = nil
}

// SetCommitMessage sets the "commit_message" field.
func (m *RetryHistoryMutation) SetCommitMessage(s string) {
	m.commit_message = &s
}

// CommitMessage returns the value of the "commit_message" field in the mutation.
func (m *RetryHistoryMutation) CommitMessage() (r string, exists bool) {
	v := m.commit_message
	if v == nil {
		return
	}
	return *v, true
}

// OldCommitMessage returns the old "commit_message" field's value of the RetryHistory entity.
// If the RetryHistory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RetryHistoryMutation) OldCommitMessage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCommitMessage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCommitMessage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCommitMessage: %w", err)
	}
	return oldValue.CommitMessage, nil
}

// ResetCommitMessage resets all changes to the "commit_message" field.
func (m *RetryHistoryMutation) ResetCommitMessage() {
	m.commit_message = nil
}

// SetCommitURL sets the "commit_url" field.
func (m *RetryHistoryMutation) SetCommitURL(s string) {
	m.commit_url = &s
}

// CommitURL returns the value of the "commit_url" field in the mutation.
func (m *RetryHistoryMutation) CommitURL() (r string, exists bool) {
	v := m.commit_url
	if v == nil {
		return
	}
	return *v, true
}

// OldCommitURL returns the old "commit_url" field's value of the RetryHistory entity.
// If the RetryHistory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RetryHistoryMutation) OldCommitURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCommitURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCommitURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCommitURL: %w", err)
	}
	return oldValue.CommitURL, nil
}

// ResetCommitURL resets all changes to the "commit_url" field.
func (m *RetryHistoryMutation) ResetCommitURL() {
	m.commit_url = nil
}

// SetPipelineName sets the "pipeline_name" field.
func (m *RetryHistoryMutation) SetPipelineName(s string) {
	m.pipeline_name = &s
}

// PipelineName returns the value of the "pipeline_name" field in the mutation.
func (m *RetryHistoryMutation) PipelineName() (r string, exists bool) {
	v := m.pipeline_name
	if v == nil {
		return
	}
	return *v, true
}

// OldPipelineName returns the old "pipeline_name" field's value of the RetryHistory entity.
// If the RetryHistory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RetryHistoryMutation) OldPipelineName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPipelineName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPipelineName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPipelineName: %w", err)
	}
	return oldValue.PipelineName, nil
}

// ResetPipelineName resets all changes to the "pipeline_name" field.
func (m *RetryHistoryMutation) ResetPipelineName() {
	m.pipeline_name = nil
}

// SetPipelineType sets the "pipeline_type" field.
func (m *RetryHistoryMutation) SetPipelineType(s string) {
	m.pipeline_type = &s
}

// PipelineType returns the value of the "pipeline_type" field in the mutation.
func (m *RetryHistoryMutation) PipelineType() (r string, exists bool) {
	v := m.pipeline_type
	if v == nil {
		return
	}
	return *v, true
}

// OldPipelineType returns the old "pipeline_type" field's value of the RetryHistory entity.
// If the RetryHistory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RetryHistoryMutation) OldPipelineType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPipelineType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPipelineType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPipelineType: %w", err)
	}
	return oldValue.PipelineType, nil
}

// ResetPipelineType resets all changes to the "pipeline_type" field.
func (m *RetryHistoryMutation) ResetPipelineType() {
	m.pipeline_type = nil
}

// Where appends a list predicates to the RetryHistoryMutation builder.
func (m *RetryHistoryMutation) Where(ps ...predicate.RetryHistory) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the RetryHistoryMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *RetryHistoryMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.RetryHistory, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *RetryHistoryMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *RetryHistoryMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (RetryHistory).
func (m *RetryHistoryMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RetryHistoryMutation) Fields() []string {
	fields := make([]string, 0, 12)
	if m.created_at != nil {
		fields = append(fields, retryhistory.FieldCreatedAt)
	}
	if m.env != nil {
		fields = append(fields, retryhistory.FieldEnv)
	}
	if m.project != nil {
		fields = append(fields, retryhistory.FieldProject)
	}
	if m.project_url != nil {
		fields = append(fields, retryhistory.FieldProjectURL)
	}
	if m.ref != nil {
		fields = append(fields, retryhistory.FieldRef)
	}
	if m.event_type != nil {
		fields = append(fields, retryhistory.FieldEventType)
	}
	if m.commit_id != nil {
		fields = append(fields, retryhistory.FieldCommitID)
	}
	if m.committer != nil {
		fields = append(fields, retryhistory.FieldCommitter)
	}
	if m.commit_message != nil {
		fields = append(fields, retryhistory.FieldCommitMessage)
	}
	if m.commit_url != nil {
		fields = append(fields, retryhistory.FieldCommitURL)
	}
	if m.pipeline_name != nil {
		fields = append(fields, retryhistory.FieldPipelineName)
	}
	if m.pipeline_type != nil {
		fields = append(fields, retryhistory.FieldPipelineType)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RetryHistoryMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case retryhistory.FieldCreatedAt:
		return m.CreatedAt()
	case retryhistory.FieldEnv:
		return m.Env()
	case retryhistory.FieldProject:
		return m.Project()
	case retryhistory.FieldProjectURL:
		return m.ProjectURL()
	case retryhistory.FieldRef:
		return m.Ref()
	case retryhistory.FieldEventType:
		return m.EventType()
	case retryhistory.FieldCommitID:
		return m.CommitID()
	case retryhistory.FieldCommitter:
		return m.Committer()
	case retryhistory.FieldCommitMessage:
		return m.CommitMessage()
	case retryhistory.FieldCommitURL:
		return m.CommitURL()
	case retryhistory.FieldPipelineName:
		return m.PipelineName()
	case retryhistory.FieldPipelineType:
		return m.PipelineType()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RetryHistoryMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case retryhistory.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case retryhistory.FieldEnv:
		return m.OldEnv(ctx)
	case retryhistory.FieldProject:
		return m.OldProject(ctx)
	case retryhistory.FieldProjectURL:
		return m.OldProjectURL(ctx)
	case retryhistory.FieldRef:
		return m.OldRef(ctx)
	case retryhistory.FieldEventType:
		return m.OldEventType(ctx)
	case retryhistory.FieldCommitID:
		return m.OldCommitID(ctx)
	case retryhistory.FieldCommitter:
		return m.OldCommitter(ctx)
	case retryhistory.FieldCommitMessage:
		return m.OldCommitMessage(ctx)
	case retryhistory.FieldCommitURL:
		return m.OldCommitURL(ctx)
	case retryhistory.FieldPipelineName:
		return m.OldPipelineName(ctx)
	case retryhistory.FieldPipelineType:
		return m.OldPipelineType(ctx)
	}
	return nil, fmt.Errorf("unknown RetryHistory field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RetryHistoryMutation) SetField(name string, value ent.Value) error {
	switch name {
	case retryhistory.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case retryhistory.FieldEnv:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEnv(v)
		return nil
	case retryhistory.FieldProject:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProject(v)
		return nil
	case retryhistory.FieldProjectURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProjectURL(v)
		return nil
	case retryhistory.FieldRef:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRef(v)
		return nil
	case retryhistory.FieldEventType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEventType(v)
		return nil
	case retryhistory.FieldCommitID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCommitID(v)
		return nil
	case retryhistory.FieldCommitter:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCommitter(v)
		return nil
	case retryhistory.FieldCommitMessage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCommitMessage(v)
		return nil
	case retryhistory.FieldCommitURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCommitURL(v)
		return nil
	case retryhistory.FieldPipelineName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPipelineName(v)
		return nil
	case retryhistory.FieldPipelineType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPipelineType(v)
		return nil
	}
	return fmt.Errorf("unknown RetryHistory field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RetryHistoryMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RetryHistoryMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RetryHistoryMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown RetryHistory numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RetryHistoryMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RetryHistoryMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RetryHistoryMutation) ClearField(name string) error {
	return fmt.Errorf("unknown RetryHistory nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RetryHistoryMutation) ResetField(name string) error {
	switch name {
	case retryhistory.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case retryhistory.FieldEnv:
		m.ResetEnv()
		return nil
	case retryhistory.FieldProject:
		m.ResetProject()
		return nil
	case retryhistory.FieldProjectURL:
		m.ResetProjectURL()
		return nil
	case retryhistory.FieldRef:
		m.ResetRef()
		return nil
	case retryhistory.FieldEventType:
		m.ResetEventType()
		return nil
	case retryhistory.FieldCommitID:
		m.ResetCommitID()
		return nil
	case retryhistory.FieldCommitter:
		m.ResetCommitter()
		return nil
	case retryhistory.FieldCommitMessage:
		m.ResetCommitMessage()
		return nil
	case retryhistory.FieldCommitURL:
		m.ResetCommitURL()
		return nil
	case retryhistory.FieldPipelineName:
		m.ResetPipelineName()
		return nil
	case retryhistory.FieldPipelineType:
		m.ResetPipelineType()
		return nil
	}
	return fmt.Errorf("unknown RetryHistory field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RetryHistoryMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RetryHistoryMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RetryHistoryMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RetryHistoryMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RetryHistoryMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RetryHistoryMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RetryHistoryMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown RetryHistory unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RetryHistoryMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown RetryHistory edge %s", name)
}
