// Code generated by ent, DO NOT EDIT.

package ent

import (
	"QuickBrick/internal/domain/ent/predicate"
	"QuickBrick/internal/domain/ent/retryhistory"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RetryHistoryDelete is the builder for deleting a RetryHistory entity.
type RetryHistoryDelete struct {
	config
	hooks    []Hook
	mutation *RetryHistoryMutation
}

// Where appends a list predicates to the RetryHistoryDelete builder.
func (rhd *RetryHistoryDelete) Where(ps ...predicate.RetryHistory) *RetryHistoryDelete {
	rhd.mutation.Where(ps...)
	return rhd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rhd *RetryHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rhd.sqlExec, rhd.mutation, rhd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rhd *RetryHistoryDelete) ExecX(ctx context.Context) int {
	n, err := rhd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rhd *RetryHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(retryhistory.Table, sqlgraph.NewFieldSpec(retryhistory.FieldID, field.TypeInt64))
	if ps := rhd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rhd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rhd.mutation.done = true
	return affected, err
}

// RetryHistoryDeleteOne is the builder for deleting a single RetryHistory entity.
type RetryHistoryDeleteOne struct {
	rhd *RetryHistoryDelete
}

// Where appends a list predicates to the RetryHistoryDelete builder.
func (rhdo *RetryHistoryDeleteOne) Where(ps ...predicate.RetryHistory) *RetryHistoryDeleteOne {
	rhdo.rhd.mutation.Where(ps...)
	return rhdo
}

// Exec executes the deletion query.
func (rhdo *RetryHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := rhdo.rhd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{retryhistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rhdo *RetryHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := rhdo.Exec(ctx); err != nil {
		panic(err)
	}
}
