// Code generated by ent, DO NOT EDIT.

package ent

import (
	"QuickBrick/internal/domain/ent/predicate"
	"QuickBrick/internal/domain/ent/retryhistory"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RetryHistoryQuery is the builder for querying RetryHistory entities.
type RetryHistoryQuery struct {
	config
	ctx        *QueryContext
	order      []retryhistory.OrderOption
	inters     []Interceptor
	predicates []predicate.RetryHistory
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RetryHistoryQuery builder.
func (rhq *RetryHistoryQuery) Where(ps ...predicate.RetryHistory) *RetryHistoryQuery {
	rhq.predicates = append(rhq.predicates, ps...)
	return rhq
}

// Limit the number of records to be returned by this query.
func (rhq *RetryHistoryQuery) Limit(limit int) *RetryHistoryQuery {
	rhq.ctx.Limit = &limit
	return rhq
}

// Offset to start from.
func (rhq *RetryHistoryQuery) Offset(offset int) *RetryHistoryQuery {
	rhq.ctx.Offset = &offset
	return rhq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rhq *RetryHistoryQuery) Unique(unique bool) *RetryHistoryQuery {
	rhq.ctx.Unique = &unique
	return rhq
}

// Order specifies how the records should be ordered.
func (rhq *RetryHistoryQuery) Order(o ...retryhistory.OrderOption) *RetryHistoryQuery {
	rhq.order = append(rhq.order, o...)
	return rhq
}

// First returns the first RetryHistory entity from the query.
// Returns a *NotFoundError when no RetryHistory was found.
func (rhq *RetryHistoryQuery) First(ctx context.Context) (*RetryHistory, error) {
	nodes, err := rhq.Limit(1).All(setContextOp(ctx, rhq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{retryhistory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rhq *RetryHistoryQuery) FirstX(ctx context.Context) *RetryHistory {
	node, err := rhq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RetryHistory ID from the query.
// Returns a *NotFoundError when no RetryHistory ID was found.
func (rhq *RetryHistoryQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = rhq.Limit(1).IDs(setContextOp(ctx, rhq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{retryhistory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rhq *RetryHistoryQuery) FirstIDX(ctx context.Context) int64 {
	id, err := rhq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RetryHistory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RetryHistory entity is found.
// Returns a *NotFoundError when no RetryHistory entities are found.
func (rhq *RetryHistoryQuery) Only(ctx context.Context) (*RetryHistory, error) {
	nodes, err := rhq.Limit(2).All(setContextOp(ctx, rhq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{retryhistory.Label}
	default:
		return nil, &NotSingularError{retryhistory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rhq *RetryHistoryQuery) OnlyX(ctx context.Context) *RetryHistory {
	node, err := rhq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RetryHistory ID in the query.
// Returns a *NotSingularError when more than one RetryHistory ID is found.
// Returns a *NotFoundError when no entities are found.
func (rhq *RetryHistoryQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = rhq.Limit(2).IDs(setContextOp(ctx, rhq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{retryhistory.Label}
	default:
		err = &NotSingularError{retryhistory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rhq *RetryHistoryQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := rhq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RetryHistories.
func (rhq *RetryHistoryQuery) All(ctx context.Context) ([]*RetryHistory, error) {
	ctx = setContextOp(ctx, rhq.ctx, ent.OpQueryAll)
	if err := rhq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RetryHistory, *RetryHistoryQuery]()
	return withInterceptors[[]*RetryHistory](ctx, rhq, qr, rhq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rhq *RetryHistoryQuery) AllX(ctx context.Context) []*RetryHistory {
	nodes, err := rhq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RetryHistory IDs.
func (rhq *RetryHistoryQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if rhq.ctx.Unique == nil && rhq.path != nil {
		rhq.Unique(true)
	}
	ctx = setContextOp(ctx, rhq.ctx, ent.OpQueryIDs)
	if err = rhq.Select(retryhistory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rhq *RetryHistoryQuery) IDsX(ctx context.Context) []int64 {
	ids, err := rhq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rhq *RetryHistoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rhq.ctx, ent.OpQueryCount)
	if err := rhq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rhq, querierCount[*RetryHistoryQuery](), rhq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rhq *RetryHistoryQuery) CountX(ctx context.Context) int {
	count, err := rhq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rhq *RetryHistoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rhq.ctx, ent.OpQueryExist)
	switch _, err := rhq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rhq *RetryHistoryQuery) ExistX(ctx context.Context) bool {
	exist, err := rhq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RetryHistoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rhq *RetryHistoryQuery) Clone() *RetryHistoryQuery {
	if rhq == nil {
		return nil
	}
	return &RetryHistoryQuery{
		config:     rhq.config,
		ctx:        rhq.ctx.Clone(),
		order:      append([]retryhistory.OrderOption{}, rhq.order...),
		inters:     append([]Interceptor{}, rhq.inters...),
		predicates: append([]predicate.RetryHistory{}, rhq.predicates...),
		// clone intermediate query.
		sql:       rhq.sql.Clone(),
		path:      rhq.path,
		modifiers: append([]func(*sql.Selector){}, rhq.modifiers...),
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RetryHistory.Query().
//		GroupBy(retryhistory.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rhq *RetryHistoryQuery) GroupBy(field string, fields ...string) *RetryHistoryGroupBy {
	rhq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RetryHistoryGroupBy{build: rhq}
	grbuild.flds = &rhq.ctx.Fields
	grbuild.label = retryhistory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.RetryHistory.Query().
//		Select(retryhistory.FieldCreatedAt).
//		Scan(ctx, &v)
func (rhq *RetryHistoryQuery) Select(fields ...string) *RetryHistorySelect {
	rhq.ctx.Fields = append(rhq.ctx.Fields, fields...)
	sbuild := &RetryHistorySelect{RetryHistoryQuery: rhq}
	sbuild.label = retryhistory.Label
	sbuild.flds, sbuild.scan = &rhq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RetryHistorySelect configured with the given aggregations.
func (rhq *RetryHistoryQuery) Aggregate(fns ...AggregateFunc) *RetryHistorySelect {
	return rhq.Select().Aggregate(fns...)
}

func (rhq *RetryHistoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rhq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rhq); err != nil {
				return err
			}
		}
	}
	for _, f := range rhq.ctx.Fields {
		if !retryhistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rhq.path != nil {
		prev, err := rhq.path(ctx)
		if err != nil {
			return err
		}
		rhq.sql = prev
	}
	return nil
}

func (rhq *RetryHistoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RetryHistory, error) {
	var (
		nodes = []*RetryHistory{}
		_spec = rhq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RetryHistory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RetryHistory{config: rhq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(rhq.modifiers) > 0 {
		_spec.Modifiers = rhq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rhq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rhq *RetryHistoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rhq.querySpec()
	if len(rhq.modifiers) > 0 {
		_spec.Modifiers = rhq.modifiers
	}
	_spec.Node.Columns = rhq.ctx.Fields
	if len(rhq.ctx.Fields) > 0 {
		_spec.Unique = rhq.ctx.Unique != nil && *rhq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rhq.driver, _spec)
}

func (rhq *RetryHistoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(retryhistory.Table, retryhistory.Columns, sqlgraph.NewFieldSpec(retryhistory.FieldID, field.TypeInt64))
	_spec.From = rhq.sql
	if unique := rhq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rhq.path != nil {
		_spec.Unique = true
	}
	if fields := rhq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, retryhistory.FieldID)
		for i := range fields {
			if fields[i] != retryhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rhq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rhq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rhq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rhq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rhq *RetryHistoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rhq.driver.Dialect())
	t1 := builder.Table(retryhistory.Table)
	columns := rhq.ctx.Fields
	if len(columns) == 0 {
		columns = retryhistory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rhq.sql != nil {
		selector = rhq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rhq.ctx.Unique != nil && *rhq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range rhq.modifiers {
		m(selector)
	}
	for _, p := range rhq.predicates {
		p(selector)
	}
	for _, p := range rhq.order {
		p(selector)
	}
	if offset := rhq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rhq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (rhq *RetryHistoryQuery) Modify(modifiers ...func(s *sql.Selector)) *RetryHistorySelect {
	rhq.modifiers = append(rhq.modifiers, modifiers...)
	return rhq.Select()
}

// RetryHistoryGroupBy is the group-by builder for RetryHistory entities.
type RetryHistoryGroupBy struct {
	selector
	build *RetryHistoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rhgb *RetryHistoryGroupBy) Aggregate(fns ...AggregateFunc) *RetryHistoryGroupBy {
	rhgb.fns = append(rhgb.fns, fns...)
	return rhgb
}

// Scan applies the selector query and scans the result into the given value.
func (rhgb *RetryHistoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rhgb.build.ctx, ent.OpQueryGroupBy)
	if err := rhgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RetryHistoryQuery, *RetryHistoryGroupBy](ctx, rhgb.build, rhgb, rhgb.build.inters, v)
}

func (rhgb *RetryHistoryGroupBy) sqlScan(ctx context.Context, root *RetryHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rhgb.fns))
	for _, fn := range rhgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rhgb.flds)+len(rhgb.fns))
		for _, f := range *rhgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rhgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rhgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RetryHistorySelect is the builder for selecting fields of RetryHistory entities.
type RetryHistorySelect struct {
	*RetryHistoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rhs *RetryHistorySelect) Aggregate(fns ...AggregateFunc) *RetryHistorySelect {
	rhs.fns = append(rhs.fns, fns...)
	return rhs
}

// Scan applies the selector query and scans the result into the given value.
func (rhs *RetryHistorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rhs.ctx, ent.OpQuerySelect)
	if err := rhs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RetryHistoryQuery, *RetryHistorySelect](ctx, rhs.RetryHistoryQuery, rhs, rhs.inters, v)
}

func (rhs *RetryHistorySelect) sqlScan(ctx context.Context, root *RetryHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rhs.fns))
	for _, fn := range rhs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rhs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rhs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (rhs *RetryHistorySelect) Modify(modifiers ...func(s *sql.Selector)) *RetryHistorySelect {
	rhs.modifiers = append(rhs.modifiers, modifiers...)
	return rhs
}
