// Code generated by ent, DO NOT EDIT.

package ent

import (
	"QuickBrick/internal/domain/ent/retryhistory"
	"QuickBrick/internal/domain/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	retryhistoryFields := schema.RetryHistory{}.Fields()
	_ = retryhistoryFields
	// retryhistoryDescCreatedAt is the schema descriptor for created_at field.
	retryhistoryDescCreatedAt := retryhistoryFields[1].Descriptor()
	// retryhistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	retryhistory.DefaultCreatedAt = retryhistoryDescCreatedAt.Default.(func() time.Time)
}
