// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// RetryHistory is the predicate function for retryhistory builders.
type RetryHistory func(*sql.Selector)
