// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// PipelineExecutionLog is the predicate function for pipelineexecutionlog builders.
type PipelineExecutionLog func(*sql.Selector)
